export const ADD_MESSAGE_START = 'ADD_MESSAGE_START';
export const ADD_MESSAGE_SUCCESS = 'ADD_MESSAGE_SUCCESS';
export const ADD_MESSAGE_FAILURE = 'ADD_MESSAGE_FAILURE';
export const TOGGLE_MESSAGE = 'TOGGLE_MESSAGE';
